### ISSUE TITLE
How can gwanjyun so strong？

### ISSUE THREAD

**Issue by TK12331** [Gwanjyun/gwanjyun_homework#2]

**Comment by Gwanjyun** [comment]
No, I am not. You are the captain of our basketball. It is you that are the strongest man.

**Comment by Gwanjyun** [comment]
> _No description provided._

No, I am not. You are the captain of our basketball. It is you that are the strongest man.

**Comment by Gwanjyun** [comment]
No, I am not. You are the captain of our school basketball team. It is you that are the strongest man.
